FROM jenkins/ssh-agent:jdk17

RUN groupadd -g 997 docker && usermod -aG docker jenkins
RUN apt-get update && apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y nodejs

RUN node --version && npm --version